version: '3.7'

x-services-defaults: &defaults
  restart: on-failure
  networks:
    - gui_ntk
  extra_hosts:
      - "host.docker.internal:host-gateway"

services:   
  api:
    <<: *defaults
    container_name: gui_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/src/
    ports:
      - "${PORT}:${PORT}"
   

networks:
  gui_ntk: {}

volumes:
  postgres: {}