version: '3.7'

x-services-defaults: &defaults
  restart: on-failure
  networks:
    - risk-gui_ntk
  extra_hosts:
      - "host.docker.internal:host-gateway"

services:   
  api:
    <<: *defaults
    container_name: gui_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - .:/src/
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db

networks:
  gui_ntk: {}

volumes:
  postgres: {}